# Generated by Django 4.2.7 on 2023-11-14 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_content_file_image_module_test_text_video_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='course',
            new_name='test',
        ),
    ]
