# Generated by Django 4.2.7 on 2023-12-10 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_usercategoryattempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubmittedanswer',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.quizcategory'),
        ),
    ]
